### ISSUE TITLE
Binding does not show up / openHAB3

### ISSUE THREAD

**Issue by OlafSc** [andrasU/openhab-free-home-binding#6]
Hi, for unknown reasons the binding does not show up in OpenHAB3 / setup step 4: The JAR is in the right directory and permissions, other JARs (like the "old" free@home binding) show up in the selection list, but the new freeathomesystem binding does not. Version 3.0.0 as downloaded today.

a required dependency seems not installed / not documented in the setup guide? 

The Apache Commons Net library | Commons Net
(from https://commons.apache.org/proper/commons-net/download_net.cgi ?)

2021-03-03 17:10:03.578 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab/addons/org.openhab.binding.freeathomesystem-3.0.0-SNAPSHOT.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.freeathomesystem [253]
  Unresolved requirement: Import-Package: org.apache.commons.net.util; version="[3.3.0,4.0.0)"

        at org.eclipse.osgi.container.Module.start(Module.java:444) ~[org.eclipse.osgi-3.12.100.jar:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) ~[org.eclipse.osgi-3.12.100.jar:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [bundleFile:3.6.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [bundleFile:3.6.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1221) [bundleFile:3.6.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:515) [bundleFile:3.6.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [bundleFile:3.6.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [bundleFile:3.6.4]

**Comment by OlafSc** [comment]
adding the commons* jar to the addons folder resolves, might want to put into the setup guide?

**Comment by andrasU** [comment]
HI,

I made some updates for the binding on Sunday. Also the update for the commons library. https://github.com/andrasU/openhab-free-home-binding/blob/main/org.openhab.binding.freeathomesystem-3.1.0-SNAPSHOT.jar <https://github.com/andrasU/openhab-free-home-binding/blob/main/org.openhab.binding.freeathomesystem-3.1.0-SNAPSHOT.jar>
Could you check the new jar file.


Somehow this is strange, but in my development environment I did not have this problem.

I would like to ask you to make a new test with then ew binary.

Thank you

**Comment by OlafSc** [comment]
yes the updated version works without having to add the commons lib.
